menu:
  Home: /
  文章: /archives
  关于: /about

widgets:
- recent_posts
- categories
- tag

excerpt_link: 阅读全文

twitter:
  username: BiqingKwok
  show_replies: false
  tweet_count: 5

facebook:
  username: biqing.kwok

google_plus:
  username: BiQingKwok

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: disqus
