menu:
  Home: /
  文章: /archives
  关于: /about
  RSS: /atom.xml

widgets:
- recent_posts
- categories
- tag
- blogroll

excerpt_link: 阅读全文

weibo:
  username: lovelovelt

github:
  username: biqing

twitter:
  username: BiqingKwok
  show_replies: false
  tweet_count: 5

facebook:
  username: biqing.kwok

google_plus:
  username: BiQingKwok

post_icon: true
post_categories:
- HTML5

baidu_share: true

fancybox: true

google_analytics:
rss: /atom.xml

comment_provider: disqus
